---
- hosts: aws
  become: yes
  tasks:
  - name: print variable
    debug:
      msg: "You requested user {{ user_to_add }}"
  - name: Creating user {{ user_to_add }}
    user:
      name: "{{ user_to_add }}"
      comment: Managed by ansible
      state: present
  - name: Removing user {{ user_to_add }}
    user:
      name: "{{ user_to_add }}"
    tags: 
      - user::remove  
